os: linux
dist: trusty

language: cpp

matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-7
            - cmake-data
            - cmake
      env:
        - COMPILER=g++-7
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - george-edison55-precise-backports
          packages:
            - clang-5.0
            - g++-5
            - cmake-data
            - cmake
      env:
        - COMPILER=clang++-5.0

compiler:
  - clang
  - gcc

#before_install:
#  - sudo apt-get install cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
