// statement


while_statement <- while ( expression ) block

do_statement <- do block while ( expression ) ;

for_statement <- 

switch_statement <-

try_statement <-

throw_statement <- throw expression ;

co_statement <- co expression ;

expression_statement <- statement_expression ;

empty_statement <- ;

// expression


statement_expression <- assignment_expression

assignment_expression <- $identifier assignment_operator expression

lambda_expression <- func ( function_call_parameter ) type_expression? block

call_expression <- 

array_access_expression <- $identifier [ expression ]

type_expression <- 

// modifier

function_modifiers <- 

variable_modifiers <-

// other


function_call_parameter <-

case_label <- case : 

default_label <- default :

assignment_operator <- | *= | /= | %= | += | -= | <<= | >>= | &= | ^= | |=

